### ISSUE TITLE
No snow is generated in modified biomes

### ISSUE THREAD

**Issue by YOUNIN15** [IMB11/SnowUnderTrees#15]
In modified biomes such as terralith, snow is not generated under the trees. I use fabric season, sometimes when I generate new fragments yes, but when it is a fragment that was loaded in spring and winter comes under the trees no snow is generated.

NOTE: I have all the terralith biomes in the configuration file.

Fabric 1.20.1 Snow Under Trees 2.5.0

**Comment by IMB11** [comment]
Snow Under Trees does not support Fabric Seasons because it's no longer maintained anymore.
