### ISSUE TITLE
[Crash] Serene Seasons API Crash if Serene Seasons is Not Installed

### ISSUE THREAD

**Issue by BlindTwig** [IMB11/SnowUnderTrees#17]
Says it in the title, if Serene Seasons isn't installed, the game will eventually crash if a snow melt is checked for. Can be worked around by disabling the season mod settings in the config, perhaps these should default to false if a season mod isn't present for the compat to hook into?

[crash-2024-08-12_20.35.32-server.txt](https://github.com/user-attachments/files/16593074/crash-2024-08-12_20.35.32-server.txt)

**Comment by IMB11** [comment]
Will fix today.
