### ISSUE TITLE
[Bug] Deadlock

### ISSUE THREAD

**Issue by TQCnoARosto** [IMB11/SnowUnderTrees#18]
World generation and world loading stop at 45%. I tried to disable the mod and world loads correctly.

[Mod list](https://pastebin.com/KxCSiMi2)
[Mod zip](https://drive.google.com/file/d/1f9QOZLuavgxLAM1UjH4Q0fAgjx5HeG8D/view?usp=sharing)

**Comment by IMB11** [comment]
Snow under trees isnt even in that mods list.

**Comment by TQCnoARosto** [comment]
I had to turn it off to open the world and use crafttweaker to list the mods, then i forgot to insert back in the list.

**Comment by TQCnoARosto** [comment]
Fixed in latest version (2.5.3)👍

**Comment by IMB11** [comment]
Great 👍
