### ISSUE TITLE
[Bug] Singleplayer World freeze like a server

### ISSUE THREAD

**Issue by Anonyku05** [IMB11/SnowUnderTrees#19]
Basically with the mod's version 2.5.1 on 1.20.4, the world entirely stops mooving like it's a server with the connection lost, and it's impossible to save the world cuz when we do, it just freeze on the world save screen and need to be closed with task manager, look at the screens:
![image](https://github.com/user-attachments/assets/a9e9ed91-9f25-4163-aaf4-0f9dfaf58f11)
![image](https://github.com/user-attachments/assets/022a4689-d18e-4deb-b40f-182611820dfd)
![image](https://github.com/user-attachments/assets/6262cdc7-77b8-4bf3-9070-d9bfb9a462a6)

Latest log file:
[latest.log](https://github.com/user-attachments/files/16627709/latest.log)

**Comment by IMB11** [comment]
Please can you upload your logs to https://mclo.gs/ - the file is too large for me to view.

**Comment by Anonyku05** [comment]
Here it is: https://mclo.gs/X2vcbx0

**Comment by IMB11** [comment]
May be a deadlock error somewhere, I will have to do some further investigating, for now, you can disable the seasons integration via the config option either in the config file or the modmenu config screen.

**Comment by IMB11** [comment]
This should be fixed in 2.5.3

**Comment by Viktordrr4** [comment]
Just want to add that disabling the season integration might not work, as it did not work for me (assuming I did it correctly).

**Comment by Thedeur** [comment]
I have this issue too, and from above users it looks like it conflicts with Serene Seasons, so thanks for at least highlighting which mod slows MC. 

I guess I'll play without this for now.

**Comment by dopemike** [comment]
Same here, same issue with snow trying to melt.

**Comment by dopemike** [comment]
https://mclo.gs/80plJuD

this is what gets put out in the "Minecraft Game Output" logger window when the mod is enabled in a snowy region while snowing

**Comment by Bobmarlinjr** [comment]
This issue is still persisting on my end, even with "respect season mods" and "melt snow seasonally" disabled.

**Comment by IMB11** [comment]
Im really sorry on how long it took me to fix this bug, it was really difficult to pin-point why the freezes were occuring.
