### ISSUE TITLE
When Serene Seasons is installed, server stalls/freezes and log gets flooded

### ISSUE THREAD

**Issue by VindSole** [IMB11/SnowUnderTrees#21]
When Serene Seasons mod is absent, mod works as intended, however if present, the server starts slowing down, or freezes entirely, like on a online lagged server, logs gets flooded with things like [Server thread/INFO]: Chance: 16 and [Server thread/INFO]: Random: 7, sometimes world gets stuck on saving and cannot be stopped without killing the process. I think it's related to the other active issue.

Log: https://mclo.gs/21OdGFh

**Comment by IMB11** [comment]
Will investigate.
