### ISSUE TITLE
Incompatible with snow! Real magic mod

### ISSUE THREAD

**Issue by ISTP7880** [IMB11/SnowUnderTrees#24]
This mode makes it simple to create snow under the tree. Snow! Real magic mod has the ability to make it look like there are plants buried in the snow, and when combined with this mode, there is no snow under the tree where the plants are, but there is snow where else is empty.

Issues about this pictures 📸 

![17325344208995687706778631061123](https://github.com/user-attachments/assets/35abb180-ecc1-4f06-a00e-38194590a2ab)

**Comment by IMB11** [comment]
There is not much I can do about this sorry, I have no clue on how to add support for Snow Real Magic, it's really up to the developer to add compatibility to mods which use normal snow during world generation.

**Comment by ISTP7880** [comment]
So, do I need to request compatibility in Snow! Real magic mode?
