### ISSUE TITLE
Snow Real Magic Mod Compatibility Fabric 1.20.1

### ISSUE THREAD

**Issue by ToppoMagico** [IMB11/SnowUnderTrees#3]
Improved snow from Snow Real Magic is not generated under trees

**Comment by mineblock11** [comment]
Link to mod? I cant find it

**Comment by AkashiiKun** [comment]
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric

**Comment by IMB11** [comment]
Same reason as Fabric Seasons - not updated past 1.20.1

**Comment by IMB11** [comment]
Will not be adding compat for Snow! Real Magic! for 1.21.x any time soon due to the complexity.
